### PR TITLE
Add Python 3.6, drop Python 3.3

### PR DESCRIPTION
**Pull request by jamadden**
- Badges
- Use zope.testrunner to fix namespace path issue
- Documentation for RTD (https://zopeprocesslifetime.readthedocs.io/en/py36)
- coveralls and coverage environment
  - 100% coverage

### CODE REVIEW

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by jamadden** [comment]
Thank you! Can we please get a PyPI release when convenient, or access to do so? It looks like only @tseaver and @strichter are PyPI owners.

**Comment by tseaver** [comment]
'jamadden' added as a PyPI Owner for `zope.processlifetime`.

**Comment by jamadden** [comment]
Thank you! 2.2.0 has been released to PyPI.

**Pull request merged**
